# Generated by Django 5.0.2 on 2024-09-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_livro_capa"),
    ]

    operations = [
        migrations.AddField(
            model_name="editora",
            name="cidade",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="editora",
            name="email",
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
